services:
  - type: web
    name: website
    env: static
    branch: master
    buildCommand: yarn && yarn export
    staticPublishPath: ./__sapper__/export
    pullRequestPreviewsEnabled: true     
  - type: web
    name: website-staging
    env: static
    branch: staging
    buildCommand: yarn && yarn export
    staticPublishPath: ./__sapper__/export
