services:
  - type: web
    name: website
    env: static
    branch: master
    buildCommand: yarn build
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: true
  - type: web
    name: website-staging
    env: static
    branch: staging
    buildCommand: yarn build
    staticPublishPath: ./public
